"""Bitbucket auto-PR: bundle every VALIDATED patch into a single pull request
whose body is an evidence table (vuln -> fix -> re-scan + test proof).

This is the payoff of the validation loop: because each patch was scanner-
reverified and test-green in a sandbox, we can open one clean PR instead of
dumping suggestions on a human. Nothing here ever touches an unvalidated patch.

Two modes:
  * git+API (default): write patches, commit to a new branch, push, open PR via
    the Bitbucket Cloud REST API.
  * --dry-run / no creds: write patches to a local branch and emit the PR body
    as markdown so the demo works fully offline.

Auth (Bitbucket Cloud), via env:
  BITBUCKET_WORKSPACE   workspace slug
  BITBUCKET_REPO        repo slug
  BITBUCKET_TOKEN       an app password or access token  (used as Bearer)
  BITBUCKET_USER        username (only needed for app-password basic auth)
"""
from __future__ import annotations

import base64
import json
import os
import subprocess
import urllib.request
from dataclasses import dataclass

API = "https://api.bitbucket.org/2.0"


@dataclass
class PrResult:
    branch: str
    title: str
    body: str
    url: str | None = None
    created: bool = False
    detail: str = ""


def build_pr_body(report) -> str:
    """Markdown evidence table over the validated fixes."""
    fixes = report.validated_fixes
    lines = [
        "## 🛡️ Patchwright — validated security fixes",
        "",
        f"Auto-fixed **{len(fixes)}** vulnerabilities. Every patch below was "
        "applied in an isolated sandbox, the **same scanner was re-run to prove "
        "the finding is gone**, and the **test suite passed** — the model never "
        "graded its own work.",
        "",
        "| Farm ID | File | Vulnerability | Fix | Confidence | Proof |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    fp_to_finding = {f.fingerprint(): f for f in report.findings}
    for p in fixes:
        f = fp_to_finding.get(p.finding_fp)
        vuln = f"{f.rule_id} ({f.severity.name})" if f else p.finding_fp
        farm = (f.farm_id if f and f.farm_id else "—")
        proof = "; ".join(e for e in p.validation_evidence) or "validated"
        rationale = p.rationale.replace("|", "\\|")
        lines.append(
            f"| {farm} | `{p.file_path}` | {vuln} | {rationale} "
            f"| {p.confidence:.0%} | {proof} |"
        )
    remaining = [f for f in report.findings
                 if f.fingerprint() not in {p.finding_fp for p in fixes}]
    if remaining:
        lines += [
            "",
            f"### {len(remaining)} finding(s) flagged for human review",
            "(no auto-fix could be *proven* safe — surfaced, never silently shipped)",
            "",
        ]
        for f in remaining[:25]:
            loc = f"{f.file_path}:{f.start_line}" if f.start_line else f.file_path
            lines.append(f"- **{f.severity.name}** {f.rule_id} — `{loc}`")
    lines += ["", "_Generated by Patchwright._"]
    return "\n".join(lines)


def _git(repo_path: str, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(["git", *args], cwd=repo_path,
                          capture_output=True, text=True)


def _auth_header() -> dict:
    token = os.environ.get("BITBUCKET_TOKEN")
    user = os.environ.get("BITBUCKET_USER")
    if token and user:                         # app-password -> basic auth
        raw = f"{user}:{token}".encode()
        return {"Authorization": "Basic " + base64.b64encode(raw).decode()}
    if token:                                  # access token -> bearer
        return {"Authorization": f"Bearer {token}"}
    return {}


def _open_pr_api(workspace: str, repo: str, branch: str, base: str,
                 title: str, body: str) -> tuple[str | None, str]:
    headers = _auth_header()
    if not headers:
        return None, "no BITBUCKET_TOKEN set; skipped API call"
    url = f"{API}/repositories/{workspace}/{repo}/pullrequests"
    payload = json.dumps({
        "title": title,
        "source": {"branch": {"name": branch}},
        "destination": {"branch": {"name": base}},
        "description": body,
        "close_source_branch": True,
    }).encode()
    req = urllib.request.Request(url, data=payload, method="POST", headers={
        **headers, "Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            data = json.loads(resp.read())
        return (data.get("links", {}).get("html", {}) or {}).get("href"), "PR created"
    except Exception as e:  # noqa: BLE001 - surface any API/network failure verbatim
        return None, f"API error: {e}"


def open_pr(repo_path: str, report, base_branch: str = "main",
            branch: str | None = None, dry_run: bool = False,
            push: bool = True) -> PrResult:
    """Write validated patches, commit to a branch, and (unless dry-run) push +
    open the PR. Returns a PrResult with the body so callers can print/save it."""
    fixes = report.validated_fixes
    branch = branch or "patchwright/auto-fixes"
    title = f"Patchwright: fix {len(fixes)} validated vulnerabilit" + \
            ("y" if len(fixes) == 1 else "ies")
    body = build_pr_body(report)
    result = PrResult(branch=branch, title=title, body=body)

    if not fixes:
        result.detail = "no validated patches to open a PR for"
        return result

    is_git = (_git(repo_path, "rev-parse", "--is-inside-work-tree").returncode == 0)
    if is_git:
        _git(repo_path, "checkout", "-B", branch)

    # write every validated patch to disk
    for p in fixes:
        target = os.path.join(repo_path, p.file_path)
        os.makedirs(os.path.dirname(target) or ".", exist_ok=True)
        with open(target, "w") as fh:
            fh.write(p.patched)

    if not is_git:
        result.detail = ("patches written, but repo is not a git checkout; "
                         "commit/PR skipped")
        return result

    _git(repo_path, "add", "-A")
    _git(repo_path, "commit", "-m", title, "-m", "Each fix scanner-reverified + tests green.")

    if dry_run or not push:
        result.detail = f"dry-run: committed to local branch '{branch}', no push"
        return result

    workspace = os.environ.get("BITBUCKET_WORKSPACE")
    repo = os.environ.get("BITBUCKET_REPO")
    pushed = _git(repo_path, "push", "-u", "origin", branch, "--force-with-lease")
    if pushed.returncode != 0:
        result.detail = f"git push failed: {pushed.stderr.strip()[:300]}"
        return result

    if workspace and repo:
        result.url, result.detail = _open_pr_api(
            workspace, repo, branch, base_branch, title, body)
        result.created = bool(result.url)
    else:
        result.detail = ("pushed branch; set BITBUCKET_WORKSPACE/BITBUCKET_REPO "
                         "to auto-open the PR")
    return result
